# Cross compilation configuration for binwalk
# https://github.com/cross-rs/cross

[target.aarch64-unknown-linux-musl]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-musl:main"
pre-build = [
    "apt-get update && apt-get install -y liblzma-dev libbz2-dev zlib1g-dev libssl-dev libfontconfig1-dev",
]

[target.aarch64-unknown-linux-musl.env]
passthrough = [
    "RUSTFLAGS",
]
